import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Comment out or remove the autogenerated sidebar
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Uncomment and modify this manual sidebar definition
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'docs', 
        'Open Code in the NHS',
        'Training & Developing Skills',
        'Developing',
        'Publishing', 

      ],
    },
    {
      type: 'category',
      label: 'Programming Languages',
      items: [
        'R', 
        'Python',
        'SQL',
      ],
    },
    {
      type: 'category',
      label: 'Web Development Frameworks',
      items: [
      'React and React Native', 
        'Angular',
        'Express.js',
        'Next.js',
        'Vue.js',
        'Remix.js',
        'Svelte'
      ],
    },
    {
      type: 'category',
      label: 'Data Visualisation Tools',
      items: [
      'Dash by Plotly', 
        'Shiny',
        'Evidence.dev',
      ],
    },
    {
      type: 'category',
      label: 'Version Control and Collaboration',
      items: [
      'Git', 
        'GitHub',
      ],
    },
    {
      type: 'category',
      label: 'Development Tools and Platforms',
      items: [
      'Jupyter Notebooks', 
        'Docker',
        'Redash'
      ],
    },
    {
      type: 'category',
      label: 'Integrated Development Environments (IDEs)',
      items: [
      'Visual Studio Code', 
      ],
    },
    {
      type: 'category',
      label: 'Artificial Intelligence and Machine Learning',
      items: [
      'AI Tools Overview', 
      'ChatGPT', 
      'Frameworks and Libraries', 
      ],
    },
    {
      type: 'category',
      label: 'Open Data and APIs',
      items: [
      'NHS Data Sources',
      'Public Health Data', 
      'APIs for Healthcare', 
      ],
    },
  ],
};

export default sidebars;
